 
GET http://localhost:3000/drafts?page=1&?limit=1
 
###
POST  http://localhost:3000/drafts/9497d186-1e30-40cd-a842-56bfb740cb2e

 
###
PATCH  http://localhost:3000/drafts/9497d186-1e30-40cd-a842-56bfb740cb2e
Content-Type: application/json

{
    "content":"angel wings, good luck babe,"
}